<?php

/**
 *  author  :   jeffstric
 *  email   :   jeffstricg@gmail.com
 *  date    :   Oct 30, 2012
 *  time    :   5:22:50 PM
 * */
function nodeTest_menu ()
{
    $items[ 'nodeTest' ] = array(
        'title' => 'nodeTest' ,
        'page callback' => 'nodeTest_overView' ,
        'access callback' => TRUE ,
    );
    return $items;
}

function nodeTest_node_info ()
{
    return array(
        'job_post' => array(
            'name' => t ('Job Post') ,
            'base' => 'job_post' ,
            'description' => t ('Use this content type to post a job.') ,
            'has_title' => TRUE ,
            'title_label' => t ('Job Title') ,
            'help' => t ('Enter the job title, job description, and the name of the company that posted the job') ,
        ) ,
    );
}

function nodeTest_overView ()
{
    node_types_rebuild ();
    $types = node_type_get_types ();
// add the body field to the node type
    node_add_body_field ($types[ 'job_post' ]);
// Load the instance definition for our content type's body
    $body_instance = field_info_instance ('node' , 'body' , 'job_post');
// Configure the body field
    $body_instance[ 'type' ] = 'text_summary_or_trimmed';
// Save our changes to the body field instance.
    field_update_instance ($body_instance);

// Create all the fields we are adding to our content type.
    foreach ( _nodeTest_installed_fields() as $field ) {
        field_create_field ($field);
    }

// Create all the instances for our fields.
    foreach ( _nodeTest_installed_instances() as $instance ) {
        $instance[ 'entity_type' ] = 'node';
        $instance[ 'bundle' ] = 'job_post';
        field_create_instance ($instance);
    }

    return '';
}

function _nodeTest_installed_fields ()
{
    $t = get_t ();
    return array(
        'job_post_company' => array(
            'field_name' => 'job_post_company' ,
            'label' => $t ('Company posting the job listing') ,
            'type' => 'text' ,
        ) ,
    );
}

function _nodeTest_installed_instances ()
{
    $t = get_t ();
    return array(
        'job_post_company' => array(
            'field_name' => 'job_post_company' ,
            'type' => 'text' ,
            'label' => $t ('Company posting the job listing') ,
            'widget' => array(
                'type' => 'text_textfield' ,
            ) ,
            'display' => array(
                'example_node_list' => array(
                    'label' => $t ('Company posting the job listing') ,
                    'type' => 'text' ,
                ) ,
            ) ,
        ) ,
    );
}

