<?php

/**
 *  author  :   jeffstric
 *  email   :   jeffstricg@gmail.com
 *  date    :   2012-12-12
 *  time    :   20:01:31
 * */

/**
 * Implementation of hook_action_info().
 */
function shopguideSnapshot_action_info()
{
    return array(
	'shopguideSnapshot_action' => array(
	    'type' => 'system' ,
	    'label' => t('distribute Image uploaded') ,
	    'configurable' => TRUE ,
	    'triggers' => array( 'node_insert' , 'node_update' , 'node_delete' ) ,
	) ,
    );
}

/**
 * Implementation of hook_action_form().
 */
function distributeImage_action_form()
{
    $query = db_select('node_type' , 'nt');
    $result = $query->fields('nt' , array( 'type' , 'name' ))
	    ->execute();

    $options = array( );
    foreach ( $result as $type ) {
	$options[ $type->type ] = $type->name;
    }

    $form[ 'node_type' ] = array(
	'#type' => 'select' ,
	'#title' => t('which node type should reseize') ,
	'#options' => $options ,
	'#default_value' => array( ) ,
	'#required' => TRUE ,
	'#description' => t('select the node type to resize') ,
	'#ajax' => array(
	    'callback' => 'distributeImage_dropdown_callback' ,
	    'wrapper' => 'dropdown_model_replace' ,
	)
    );

    // if ajax precess , we can get $nodeType , so we can use this to distinguish ajax or the normal
    $nodeType = (isset($form_state[ 'values' ][ 'node_type' ]) ) ? $form_state[ 'values' ][ 'node_type' ] : key($options);
    $options = array( );

    $query = db_select('field_config_instance' , 'fci');
    $result = $query->fields('fci' , array( 'field_name' ))
	    ->condition('bundle' , $nodeType)
	    ->execute();

    foreach ( $result as $value ) {
	$options[ $value->field_name ] = $value->field_name;
    }


    $form[ 'field_type' ] = array(
	'#type' => 'select' ,
	'#title' => t('which field type should reseize') ,
	'#options' => $options ,
	'#default_value' => key($options) ,
	'#required' => TRUE ,
	'#description' => t('select the node type to resize') ,
	'#prefix' => '<div id="dropdown_model_replace">' ,
	'#suffix' => '</div>' ,
    );

    $form[ '#submit' ][ ] = 'distributeImage_add_submit';

    return $form;
}

function distributeImage_dropdown_callback( $form , $form_state )
{
    return $form[ 'field_type' ];
}

function distributeImage_add_submit( $form , $form_state )
{
//    $result = db_query('SELECT count(sir_id) AS result FROM `' . RESEIZEIMG_TABLENAME .
//	    '` WHERE sir_node_type = :sir_node_type AND sir_image_fieldname = :sir_image_fieldname' , array(
//	':sir_node_type' => $form_state[ 'values' ][ 'node_type' ] ,
//	':sir_image_fieldname' => $form_state[ 'values' ][ 'field_type' ]
//	    ))->fetch();
//
//    if ( !$result->result ) {
//	$sid = db_insert(RESEIZEIMG_TABLENAME)
//		->fields(array(
//		    'sir_node_type' => $form_state[ 'values' ][ 'node_type' ] ,
//		    'sir_image_fieldname' => $form_state[ 'values' ][ 'field_type' ] ,
//		    'sir_thumb_width' => $form_state[ 'values' ][ 'width' ] ,
//		    'sir_thumb_height' => $form_state[ 'values' ][ 'height' ] ,
//		))
//		->execute();
//    }
}

