<?php

/**
 *  @file
 *  bababababa 
 * 
 *  description
 */
function annotate_menu(){
    $item['admin/config/annotate']=array(
        'title'=>'Node annotate',
        'description'   =>'Adjust node annotate option.',
        'position'=>'right',
        'weight'=>'-5',
        'page callback'=>'system_admin_menu_block_page',
        'access arguments'=>array('administer site configuration'),
        'file'=>'system.admin.inc',
        'file_path'=>drupal_get_path('module','system'),
    );
    $item['admin/config/annotate/settings']=array(
        'title'=>'Annotate setting',
        'description'   =>'Change how annotate behave.',
        'page callback'=>'drupal_get_form',
        'page arguments'=>array('annotate_admin_settings'),
        'access arguments'=>array('administer site configuration'),
        'type'=>MENU_NORMAL_ITEM,
        'file'=>'annotate.admin.inc',
    );
    
    return $item;
}