<?php

/**
 *  author  :   jeffstric
 *  email   :   jeffstricg@gmail.com
 *  date    :   Nov 14, 2012
 *  time    :   1:38:38 PM
 * */
/**
 * @file
 *
 * 
 */
define('TOPIC_ARTICLE_TYPE' , 'topic_articles');
define('VARIABLE_GUIDE_NAME' , 'homepage_guide');

/**
 * Implementation of hook_menu().
 */
function homepageGuide_menu()
{
    $items[ 'admin/config/homepage' ] = array(
	'title' => 'homepage setting' ,
	'description' => 'Adjust homepage options.' ,
	'position' => 'right' ,
	'weight' => -5 ,
	'page callback' => 'system_admin_menu_block_page' ,
	'access arguments' => array( 'administer site configuration' ) ,
	'file' => 'system.admin.inc' ,
	'file path' => drupal_get_path('module' , 'system') ,
    );
    $items[ 'admin/config/homepage/guide' ] = array(
	'title' => 'homepage guide' ,
	'description' => 'Change how annotations behave.' ,
//        'page callback' => 'homepageGuide_hello' ,
	'page callback' => 'drupal_get_form' ,
	'page arguments' => array( 'homepageGuide_admin_settings' ) ,
	'access arguments' => array( 'administer site configuration' ) ,
	'type' => MENU_NORMAL_ITEM ,
	'file' => 'homepageGuide.admin.inc' ,
    );

    return $items;
}

function homepageGuide_list()
{
// Use the Database API to retrieve our data.
// @see http://drupal.org/node/310069

    $guideArticleId = variable_get(VARIABLE_GUIDE_NAME);

    $query = db_select('node' , 'n');

    $query->join('field_data_field_topic_article_image' , 'i' , 'n.nid = i.entity_id');
    $query->join('file_managed' , 'm' , 'i.field_topic_article_image_fid = m.fid');
    $query->addField('m' , 'uri' , 'src');
    $query->addField('i' , 'field_topic_article_image_alt' , 'alt');

    $query->fields('n' , array( 'title' , 'nid' , 'created' ))
	    ->fields('i' , array( 'field_topic_article_image_fid' ))
	    ->condition('n.nid' , $guideArticleId)
	    ->orderBy('created' , 'DESC')
	    ->range(0 , 6);

    $result = $query->execute();

    return $result;
}

/**
 * Implements hook_block_info().
 */
function homepageGuide_block_info()
{
    $blocks = array( );
// The array key defines the $delta parameter used in all
// other block hooks.
    $blocks[ 'homepageGuide' ] = array(
// The name of the block on the blocks administration page.
	'info' => 'homepageGuide' ,
	'cache' => DRUPAL_CACHE_PER_ROLE ,
//	'cache' => DRUPAL_NO_CACHE , //develop environment
    );
    return $blocks;
}

/**
 * Implements hook_block_view().
 *
 *  * First draft!
 *
 * @pararm $delta
 *   The name of the requested block.
 */
function homepageGuide_block_view( $delta = '' )
{
// Create an empty block.
    $block = array(
	'subject' => 'homepageGuide title' ,
	'content' => 'homepageGuide content' ,
    );
    $items = array(
	'title' => '' ,
	'type' => 'ul' ,
	'items' => homepageGuide_list()
    );
    if ( !empty($items[ 'items' ]) ) {
	$block[ 'content' ] = theme('homepageGuideOutput' , $items);
    }
    return $block;
}

function homepageGuide_theme()
{
    return array(
	'homepageGuideOutput' => array(
	    'variables' => array( 'items' => array( ) ) ,
	) ,
    );
}

function theme_homepageGuideOutput( $variables )
{
//    dpm($variables);
    $items = $variables[ 'items' ];
    $title = $variables[ 'title' ];
    $type = $variables[ 'type' ];

    $output = <<<EOE
   <div class="content">
    <div id="featureNormal" style="background:url(http://files.smarter.com/images/v6/smarter_blogs_20120827.jpg) no-repeat;">
	<div id="featurepopup" style="height: 48px; display: block;">
	    <div class="featurePng"><img src="http://files.smarter.com/images/v6/featureBannerBg.png" alt="" width="328" height="199"></div>
	    <div class="featurePopupText">
		<div class="featurePopupTitle"><a href="/shopping-guides/" target="_blank">SMART GUIDES</a></div>
		<h3>latest update:</h3>
		    <div class="blogcontent">
EOE;
    foreach ( $items as $item ) {
	$item->alt = $item->alt ? $item->alt : $item->name;
	$item->src = file_create_url($item->src);
	$item->url = file_create_url( 'node/' . $item->nid);
	$output.='
		    <div class="blogitem" style="display: none;">
			<div class="featurePic">
			    <table><tbody><tr><td valign="middle"><img src=" ' . $item->src . '" alt="' . $item->alt . '" style="height: 104px;"></td></tr></tbody></table>
			</div>
			<p>
			    <a href="' . $item->url . '" target="_blank">' . $item->title . '.</a>
			</p>
		    </div>
	    ';
    }
    $output .=<<<EOT
		    </div>
		<div class="featureChange"><a href="#" class="prev">Prev</a><a href="#" class="next nextNo">Next</a></div>
	    </div>
	    <!-- end featurePopupText -->
	</div>
	<!-- end featurepopup --> 
    </div> 
</div>
EOT;
    return $output;
}

