<?php

/**
 *  author  :   jeffstric
 *  email   :   jeffstricg@gmail.com
 *  date    :   Nov 14, 2012
 *  time    :   1:38:38 PM
 * */
/**
 * @file
 * * Enables a single-user blog.
 */

/**
 * Returns a list of blog entries.
 *
 * @param $number
 *   The number of blog entries to return.
 * @return
 *   A result set object containing the list of blog entries.
 */
function homepageGuide_list( $number )
{
// Use the Database API to retrieve our data.
// @see http://drupal.org/node/310069
//    $query = db_select('node' , 'n')
//	    ->fields('n' , array( 'nid' , 'title' , 'created' , 'uid' ))
//	    ->condition('type' , homepageGuide_NODE_TYPE)
//	    ->condition('status' , 1)
//	    ->orderBy('created' , 'DESC')
//	    ->range(0 , $number)
//	    ->addTag('node_access')
//	    ->execute();
//    return $query;
}

/**
 * Implements hook_block_info().
 */
function homepageGuide_block_info()
{
    $blocks = array( );
// The array key defines the $delta parameter used in all
// other block hooks.
    $blocks[ 'homepageGuide' ] = array(
// The name of the block on the blocks administration page.
	'info' => 'homepageGuide' ,
    );
    return $blocks;
}

/**
 * Implements hook_block_view().
 *
 *  * First draft!
 *
 * @pararm $delta
 *   The name of the requested block.
 */
function homepageGuide_block_view( $delta = '' )
{
// Create an empty block.
    $block = array(
	'subject' => 'homepageGuide title' ,
	'content' => 'homepageGuide content' ,
    );
//// Check which block is being requested.
//    if ( $delta == 'recent' ) {
//// Set the block title.
//	$block[ 'subject' ] = t('Recent blog posts');
//// Check if the user can access content.
//	if ( user_access('access content') ) {
//// Retrieve the most recent nodes.
//	    $result = homepageGuide_list(homepageGuide_LIST_COUNT);
//// Create links for each blog entry.
//	    $items = array( );
//	    foreach ( $result as $node ) {
//		$items[ ] = array(
//		    'data' => l($node->title , 'node/' . $node->nid) ,
//		    'class' => array( 'node-' . $node->nid ) ,
//		);
//	    }
//	    if ( !empty($items) ) {
//// Theme the list of blog entries.
//		$block[ 'content' ] = theme('item_list' , array(
//		    'items' => $items ));
//	    }
//	}
//    }
    return $block;
}