<?php

/**
 *  author  :   jeffstric
 *  email   :   jeffstricg@gmail.com
 *  date    :   Oct 23, 2012
 *  time    :   2:26:00 PM
 * */
/**
 * @file
 * image resize
 */
define('RESEIZEIMG_CLASS_FILENAME' , 'ThearchyImg.php');
define('RESEIZEIMG_TABLENAME' , 'smarter_image_reseize');

/**
 * Implementation of hook_action_info().
 */
function reseizeImg_action_info()
{
    return array(
	'reseizeImg_action' => array(
	    'type' => 'system' ,
	    'label' => t('reseize img') ,
	    'configurable' => FALSE ,
	    'triggers' => array( 'node_insert' , 'node_update' , 'node_delete' ) ,
	) ,
    );
}

function reseizeImg_menu()
{
    $items[ 'admin/config/media/reseizeImg' ] = array(
	'title' => 'list resize image rule' ,
	'description' => 'list reseize rules' ,
	'page callback' => 'reseizeImg_rule_list' ,
	'access arguments' => array( 'administer site configuration' ) ,
	'type' => MENU_NORMAL_ITEM ,
	'file' => 'reseizeImg.manage.inc' ,
    );
    $items[ 'admin/config/media/reseizeImg/delete/%' ] = array(
	'title' => 'manage resize image rule' ,
	'description' => 'manage reseize rules' ,
	'page callback' => 'reseizeImg_delete' ,
	'page arguments' => array( 5 ) ,
	'access arguments' => array( 'administer site configuration' ) ,
	'type' => MENU_NORMAL_ITEM ,
    );
    $items[ 'admin/config/media/reseizeImg/add' ] = array(
	'title' => 'add resize image rule' ,
	'description' => 'chose which field image should reseize' ,
	'page callback' => 'drupal_get_form' ,
	'page arguments' => array( 'reseizeImg_add_settings' ) ,
	'access arguments' => array( 'administer site configuration' ) ,
	'type' => MENU_NORMAL_ITEM ,
	'file' => 'reseizeImg.add.inc' ,
    );

    return $items;
}

function reseizeImg_action()
{
    $input = func_get_arg(1);
    $nodes = $input[ 'node' ];

    $query = db_select(RESEIZEIMG_TABLENAME , 'sir');
    $result = $query->fields('sir')
	    ->execute();

    $nodeReseizeList = array( );
    /**
     * array key :  content type    |  in datebase  is  table :node_type , clumn : type 
     * imageFieldName : image field  |  in database is table:field_config ,clumn : field_name
     */
    foreach ( $result as $value ) {
	$nodeReseizeList[ $value->sir_node_type ] = array(
	    'imageFieldName' => $value->sir_image_fieldname ,
	    'thumbSize' => array( $value->sir_thumb_width , $value->sir_thumb_height ) ,
	);
    }



    if ( in_array($nodes->type , array_keys($nodeReseizeList)) ) {

	$imageKey = $nodeReseizeList[ $nodes->type ][ 'imageFieldName' ];
	$images = $nodes->$imageKey;
	$triggle = $input[ 'hook' ];
	$type = $nodes->type;
	unset($nodes);
	unset($input);

	$imageIds = array( );

	foreach ( $images[ 'und' ] as $value ) {
	    array_push($imageIds , $value[ 'fid' ]);
	}

	//get image dirctory
	$query = db_select('field_config_instance' , 'c');
	$result = $query->fields('c' , array( 'data' ))->condition('field_name' , $nodeReseizeList[ $type ][ 'imageFieldName' ])->execute()->fetchAssoc();

	$dir = unserialize($result[ 'data' ]);
	$file_directory = DRUPAL_ROOT . '/sites/default/files/' . $dir[ 'settings' ][ 'file_directory' ] . '/';
	unset($dir);

	//get images filename
	$query = db_select('file_managed' , 'f');
	$result = $query->fields('f' , array( 'filename' ))->condition('fid' , $imageIds)->execute();

	$imageSeize = $nodeReseizeList[ $type ][ 'thumbSize' ];

	require_once dirname(__FILE__) . '/' . RESEIZEIMG_CLASS_FILENAME;
	$ThearchyImg = new ThearchyImg();

	if ( $triggle == 'node_update' || $triggle == 'node_insert' ) {
	    foreach ( $result as $value ) {
		$fileThumb = $file_directory . reseizeImg_getThumbName($value->filename);
		if ( !file_exists($fileThumb) )
		    $ThearchyImg->resize(
			    $fileThumb , $file_directory . $value->filename , $imageSeize[ 0 ] , $imageSeize[ 1 ]
		    );
	    }
	}elseif ( $triggle == 'node_delete' ) {
	    foreach ( $result as $value ) {
		$fileThumb = $file_directory . reseizeImg_getThumbName($value->filename);
		unlink($fileThumb);
	    }
	}
    }
}

function reseizeImg_rule_list()
{

    $query = db_select(RESEIZEIMG_TABLENAME , 'sir');
    $query->addField('sir' , 'sir_id' , 'id');
    $query->addField('sir' , 'sir_node_type' , 'type');
    $query->addField('sir' , 'sir_image_fieldname' , 'field');
    $query->addField('sir' , 'sir_thumb_width' , 'width');
    $query->addField('sir' , 'sir_thumb_height' , 'height');
    $result = $query->execute();

    $header = array(
	'type' => array( 'data' => 'node type' ) ,
	'field' => array( 'data' => 'image field name' ) ,
	'width' => array( 'data' => 'width' ) ,
	'height' => array( 'data' => 'height' ) ,
	'delete' => array( 'data' => 'delete' ) ,
    );
    $rows = array( );

    foreach ( $result as $key => $value ) {
	$rows[ ] = array(
	    'data' => array(
		array( 'data' => $value->type ) ,
		array( 'data' => $value->field ) ,
		array( 'data' => $value->width ) ,
		array( 'data' => $value->height ) ,
		array( 'data' => l('delete' , file_create_url('admin/config/media/reseizeImg/delete/') . $value->id) ) ,
	    ) ,
	);
    }


    $table = array(
	'#prefix' => l('create rule' , file_create_url('admin/config/media/reseizeImg/add')) ,
	'#theme' => 'table' ,
	'#rows' => $rows ,
	'#header' => $header ,
    );

    return drupal_render($table);

//    return $output;
}

function reseizeImg_delete( $sir_id )
{
    $sir_id = (int) $sir_id;
    $result = db_delete(RESEIZEIMG_TABLENAME)
	    ->condition('sir_id' , $sir_id)
	    ->execute();
    drupal_goto('admin/config/media/reseizeImg/list');
}

function reseizeImg_getThumbName( $filename )
{
    $strArray = explode('.' , $filename);
    $lastSecondIndex = count($strArray) - 2;
    array_splice($strArray , $lastSecondIndex , 1 , $strArray[ $lastSecondIndex ] . '_thumb');
    return implode('.' , $strArray);
}

