<?php

/**
 * author:jeffstric
 * email:jeffstricg@gmail.com
 * blog:jeffsc.info
 * datetime:2012-10-28, 21:38:13
 * */
function mysite_preprocess_node( &$variables )
{
// Add taxonomy-based classes to the node markup.
    if(isset($variables['field_category'])){
	foreach ( $variables[ 'field_category' ] as $term ) {
	    $variables[ 'classes_array' ][ ] = 'taxonomy-' . $term[ 'tid' ];
	}
    }
}

?>