<?php

/**
 *  author  :   jeffstric
 *  email   :   jeffstricg@gmail.com
 *  date    :   Nov 29, 2012
 *  time    :   10:04:22 AM
 * */
/**
 * Implements hook_field_schema().
 */
if ( !defined('SHOP_ITEM_ID_SUFFIX') ) {
    require 'shoppingGuide.module';
}
function shoppingGuide_field_schema( $field )
{
    $columns = array(
	SHOP_ITEM_ID_SUFFIX => array(
	    'type' => 'int' ,
	    'unsigned' => TRUE ,
	    'not null' => TRUE ,
	) ,
    );

    return array(
	'columns' => $columns ,
    );
}